onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - rclone.js
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
catalog:
  '@ai-sdk/openai': ^2.0.77
  '@antfu/eslint-config': ^6.4.2
  '@ast-grep/napi-darwin-arm64': ^0.40.0
  '@ast-grep/napi-linux-x64-gnu': ^0.40.0
  '@cloudflare/puppeteer': ^1.0.4
  '@echristian/edge-tts': ^0.0.14
  '@eslint-react/eslint-plugin': ^2.3.12
  '@opennextjs/cloudflare': ^1.14.3
  '@radix-ui/react-slot': ^1.2.4
  '@tailwindcss/postcss': ^4.1.17
  '@tanstack/react-store': ^0.8.0
  '@tanstack/store': ^0.8.0
  '@types/markdown-it': ^14.1.2
  '@types/node': <23
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vidstack/react': ^1.12.13
  ai: ^5.0.107
  cheerio: ^1.1.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  eslint: ^9.39.1
  eslint-config-next: ^15.5.7
  eslint-plugin-better-tailwindcss: ^3.7.11
  eslint-plugin-format: ^1.1.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  i18next: ^25.7.1
  i18next-browser-languagedetector: ^8.2.0
  lint-staged: ^16.2.7
  lucide-react: ^0.556.0
  markdown-it: ^14.1.0
  media-icons: ^1.1.5
  motion: ^12.23.25
  next: ^15.5.7
  ofetch: ^1.5.1
  podcast: ^2.0.1
  postcss: ^8.5.6
  puppeteer: 22.8.2
  react: ^19.2.1
  react-dom: ^19.2.1
  react-i18next: ^16.4.0
  react-markdown: ^10.1.0
  remark-gfm: ^4.0.1
  simple-git-hooks: ^2.13.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vidstack: ^1.12.13
  wrangler: ^4.53.0
  zod: ^4.1.13
