allowBuilds:
  esbuild: true
  puppeteer: true
  sharp: true
  simple-git-hooks: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - puppeteer
  - rclone.js
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
